default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost

development:
  <<: *default
  database: ge-lookup_development
  username: ben
  password: ben
  host: localhost

test:
  <<: *default
  database: ge-lookup_test
  username: ben
  password: ben
  host: localhost

production:
  <<: *default
  database: ge-lookup_production
  username: ge-lookup
  password: <%= ENV['GE-LOOKUP_DATABASE_PASSWORD'] %>
